import moment from 'moment';

const locations = [
  {
    id: 1,
    image: '/locations/playa.jpg',
    hidden: false,
    title: 'Playa de Las Canteras',
    timeDuration: 25,
    position: {lat: 28.140578, lng: -15.435765},
    description: "Locals keep saying Las Canteras is one of the nation’s best urban beaches. And they have every reason to believe it. This is a beach blessed with fine weather practically all year round. A getaway within the capital city, a place where the hands of time seem to have stopped. A type of beach-style Central Park, where sports can be played any day of the week. Don’t forget your swimming clothes and your surf board! Furthermore, the island is a large marine life reserve. Its sea bed is home to a thousand fish species. On dry land, it shelters tourists, fishermen, and surfers. And it has a peculiar feature, which locals know as “La Barra”, a long rock formation spreading not far from the sand. A singular strip of volcanic rock that protects a large chunk of the beach from the tides, and which turns our bay into the best place this side of the globe to swim and practically “walk on the water” on days of low tide.",
    comments: [{
      username: "Anonymous", comment: "it's great", date: moment()
    }],
    distance: null,
  },
  {
    id: 2,
    image: '/locations/vegueta.jpg',
    hidden: false,
    title: 'Vegueta',
    timeDuration: 35,
    position: {lat: 28.098467, lng: -15.415550},
    description: "This is a district",
    comments: [],
    distance: null,
  },
  {
    id: 3,
    image: '/locations/jardin.jpg',
    hidden: false,
    title: 'Jardin Canario',
    timeDuration:55,
    position: {lat: 28.066520, lng: -15.456779},
    description: "This is a botanic garden",
    comments: [],
    distance: null,
  },
  {
    id: 4,
    image: '/locations/colon.jpg',
    hidden: false,
    title: 'Casa de Colon',
    timeDuration: 60,
    position: {lat: 28.101583, lng: -15.414071},
    description: "This is a house",
    comments: [],
    distance: null,
  },
  {
    id: 5,
    image: '/locations/bandama.jpg',
    hidden: false,
    title: 'Caldera de Bandama',
    timeDuration: 86,
    position: {lat: 28.031720, lng: -15.455764},
    description: "This is a volcano",
    comments: [],
    distance: null,
  },
  {
    id: 6,
    image: '/locations/triana.jpg',
    hidden: false,
    title: 'Calle Triana',
    timeDuration: 120,
    position: {lat: 28.106050, lng: -15.416341},
    description: "No idea what is it",
    comments: [],
    distance: null,
  },
  {
    id: 7,
    image: '/locations/doramas.jpg',
    hidden: false,
    title: 'Doramas Park',
    timeDuration: 380,
    position: {lat: 28.078, lng: -15.5889},
    description: "This is a park",
    comments: [],
    distance: null,
  },
  {
    id: 8,
    image: '/locations/museo.jpg',
    hidden: false,
    title: 'Museo Elder de la Ciencia y la Tecnologia',
    timeDuration: 280,
    position: {lat: 28.140908, lng: -15.429839},
    description: "This is a museum",
    comments: [],
    distance: null,
  },
  {
    id: 9,
    image: '/locations/centro_comercial_las_arenas.jpg',
    hidden: false,
    title: 'Centro Comercial Las Arenas',
    timeDuration: 45,
    position: {lat: 28.128353, lng: -15.448291},
    description: "This is a mall",
    comments: [],
    distance: null,
  },
  {
    id: 10,
    image: '/locations/cathedral.jpg',
    hidden: false,
    title: 'Catedral de Santa Ana',
    timeDuration: 150,
    position: {lat: 28.100814, lng: -15.414767},
    description: "This is a cathedral",
    comments: [],
    distance: null,
  },
];

export default locations;
